### ISSUE TITLE
Keyboard shorcut not working

### ISSUE THREAD

**Issue by trebmuh** [brummer10/GxFenderizer.lv2#2]
Hi Hermann

Looks like the SHIFT+TAB [keyboard shortcut mentioned in the README](https://github.com/brummer10/GxFenderizer.lv2#keyboard-shortcuts) doesn't work here. Please, note that:
* the TAB shortcut works fine here
* the SHIFT+TAB shortcut work fine with (e.g.) GxZoom

HTH

**Comment by brummer10** [comment]
That's strange, SHIFT+TAB works fine here as well.

**Comment by trebmuh** [comment]
Not a big deal. Just strange :)

Note that I'm using MATE 1.20.4 if that can be of help. Do not hesitate to ask for more info if you want.

Don't rush onto this, I'm not using the shortcut usually. I just found out while doing a review of the plug.

Thanks for all your amazing plugs!

**Comment by brummer10** [comment]
Yes, thanks for reporting, after a short look on the source I've already a idea what it could be.
Will push a fix tomorrow.

**Comment by trebmuh** [comment]
OK, Count on me for trying it.

**Comment by brummer10** [comment]
So I've pushed a possible Fix for the shortcut to the repository. 
Additional there is now a switch to select between Crunch and clean mode, as requested by @Houston4444
https://linuxmusicians.com/viewtopic.php?p=127944#p127944

**Comment by trebmuh** [comment]
> So I've pushed a possible Fix for the shortcut to the repository.

The fix is working. Thanks!

>  Additional there is now a switch to select between Crunch and clean mode [...]

Sounds to me that the "crunch" selection is sounding like clean, and the "clean" selection is sounding like crunch. Isn't?

**Comment by brummer10** [comment]
Thanks for reporting back that the fix for the keyboard works.
And indeed I've switched the clean/crunch selector the wrong way, it's fixed in the repository now.

**Comment by trebmuh** [comment]
Just tested and all good now.
Thanks for the quick fix.
